s3 api not allow to delete over 1k obj at once, rename op may trigger…
PaddlePaddle/PaddleFlow pull request #1081
Opened 2023-03-21 08:37 UTC by caizejun

… this restriction

### PR types
 Bug fixes

### PR changes
APIs
### Describe
s3 api not allow to delete over 1k obj at once, rename op may trigger…

2023-03-22 07:58 UTC, luoyuedong requested changes

2023-03-22 07:58 UTC, luoyuedong commented on pkg/fs/client/ufs/object.go
> +func (fs *objectFileSystem) CopyTask(content object.ItemOutput, prefix, newPrefix string,
这里为啥要单独建个函数，参数太多，copy锁很容易出问题的

2023-03-22 07:58 UTC, luoyuedong commented on pkg/fs/client/ufs/object.go
> +			return errBuf[0]
这里errBuf不是这么写的，让你返回所有的报错，不是第一个报错
var errBuf bytes.Buffer
errBuf.WriteString(err.Error())
errBuf.WriteString(";")

    if errBuf.Len() > 0 {
        return nil, fmt.Errorf(errBuf.String())
    }

2023-03-22 07:58 UTC, luoyuedong commented on pkg/fs/client/ufs/object.go
> +			wg.Done()
直接函数开头写defer wg.Done

2023-03-22 07:58 UTC, luoyuedong commented on pkg/fs/client/ufs/object.go
> +		if len(errBuf) != 0 {
加上日志log.Errof

2023-03-22 07:58 UTC, luoyuedong commented on pkg/fs/client/ufs/object.go
> +			wg.Add(1)
这里并发确定没有问题，content并发不会被修改吗？

2023-03-22 07:59 UTC, luoyuedong requested changes

2023-03-22 07:59 UTC, luoyuedong commented on pkg/fs/client/ufs/object.go
> +	p, _ := ants.NewPool(10)
10这么少？至少1000吧

2023-03-22 08:01 UTC, luoyuedong requested changes

2023-03-22 08:01 UTC, luoyuedong commented on pkg/fs/client/ufs/object/bos.go
> +			}
日志

2023-03-22 08:01 UTC, luoyuedong commented on pkg/fs/client/ufs/object/bos.go
> +			if res != nil { //部分删除成功
错误日志

2023-03-23 02:34 UTC, caizejun commented on pkg/fs/client/ufs/object/bos.go
> +			}
ok

2023-03-23 02:47 UTC, luoyuedong approved these changes

2023-03-23 03:03 UTC, tornado404 approved these changes
1

2023-03-23 06:00 UTC, merged