PGSQL initialization script,paddleflow.sql Supports versions of pgSQL…
PaddlePaddle/PaddleFlow pull request #1209
Opened 2023-07-28 07:35 UTC by liujiaxing123666

### PR types

1
### PR changes

1
### Describe

2023-07-28 07:45 UTC, luoyuedong approved these changes

2023-07-31 02:20 UTC, D0m021ng approved these changes
LGTM

2023-07-31 02:31 UTC, D0m021ng requested changes

2023-07-31 02:31 UTC, D0m021ng commented on installer/database/execute.sh
> +elif [[ $DB_DRIVER = "postgres" ]];then
`$DB_DRIVER == "postgresql"`

2023-07-31 06:48 UTC, D0m021ng approved these changes

2023-07-31 09:10 UTC, merged