update PF_RUN_TIME
PaddlePaddle/PaddleFlow pull request #156
Opened 2022-04-21 11:53 UTC by HaozhengAN

2022-04-21 12:48 UTC, Mo-Xianyuan requested changes

2022-04-21 12:48 UTC, Mo-Xianyuan commented on pkg/pipeline/common/envHandler.go
> +func GetPFRuntime(stepName string, runtimeView schema.RuntimeView, workflowSource schema.WorkflowSource) (string, error) {
建议封装成类，以及补充注释，说明一些要点

2022-04-21 12:48 UTC, Mo-Xianyuan commented on pkg/apiserver/models/run.go
> +func (r *Run) initAllPFRuntime() error {
村jobview的时候，是否已经吧pf_run_time过滤了？

2022-04-22 02:35 UTC, Mo-Xianyuan requested changes

2022-04-22 02:35 UTC, Mo-Xianyuan commented on pkg/pipeline/common/envHandler.go
> +	workflowSource schema.WorkflowSource
jobview里面也有deps，是不是可以直接根据runtimeview，对stepName做校验，以及获取deps？而不是额外使用worflowsource？

2022-04-22 02:43 UTC, HaozhengAN commented on pkg/pipeline/common/envHandler.go
> +	workflowSource schema.WorkflowSource
1、runtimeview 中没有 post_process 中的任何信息
2、workflowSource 提供了对于 deps 的解析逻辑，使用该参数可以直接复用该逻辑
3、在 job 运行前， 我们需要获取 PF_RUN_TIME 的信息，此时 runtimeview 可能并没有当前节点对应的 jobView 信息（1.4.2 计划这么实现）

2022-04-22 02:52 UTC, Mo-Xianyuan approved these changes

2022-04-22 03:05 UTC, merged