Go SDK: go-sdk add Run and Pipeline interface
PaddlePaddle/PaddleFlow pull request #357
Opened 2022-06-16 08:16 UTC by HaozhengAN

2022-06-17 03:35 UTC, StevenYangCao commented on pkg/common/schema/workflow.go
>  }
这个名字建议先不改，改完之后，其他所有地方，包括现在正在开发的部分也要跟着改

2022-06-17 03:35 UTC, StevenYangCao commented on pkg/common/schema/workflow.go
> +func ParseWorkflowSourceWithOutTransOutputArtifact(runYaml []byte) (WorkflowSource, error) {
WithOut->Without

2022-06-20 03:20 UTC, Mo-Xianyuan requested changes

2022-06-20 03:20 UTC, Mo-Xianyuan commented on go-sdk/pipeline/pipeline.go
> +func TransPipelineToYamlRaw(p *Pipeline) (runYamlRaw string, err error) {
这个做成成员函数吧，只有拥有了pipeline对象，才能够掉用这个函数。另外workflowsource应该是有序列化的函数，可以看看是否能复用

2022-06-20 03:20 UTC, Mo-Xianyuan commented on go-sdk/pipeline/pipeline.go
> +type Step = schema.WorkflowSourceStep
这个定义没有用到？

2022-06-20 03:20 UTC, Mo-Xianyuan commented on go-sdk/pipeline/pipeline.go
> +func validatePipeline(pipeline *schema.WorkflowSource) (err error) {
schema.WorkflowSource Pipeline，尽量统一使用哪个type

2022-06-20 06:14 UTC, Mo-Xianyuan approved these changes

2022-06-20 06:51 UTC, merged