feature: uninstall paddlelfow storage
PaddlePaddle/PaddleFlow pull request #841
Opened 2022-10-26 07:32 UTC by caizejun

### PR types
[New features

### PR changes
APIs

### Describe
add python-shell for uninstall storage

2022-10-26 08:21 UTC, ElsieFan approved these changes

2022-10-26 09:08 UTC, luoyuedong approved these changes

2022-11-08 09:27 UTC, tornado404 requested changes

2022-11-08 09:27 UTC, tornado404 commented on uninstaller/pre-delete.py
> +from logging import root
这个包没看到使用，是否删除

2022-11-08 09:33 UTC, caizejun commented on uninstaller/pre-delete.py
> +from logging import root
已删除

2022-11-08 09:40 UTC, tornado404 approved these changes
OK

2022-11-08 09:53 UTC, merged