add Get func to ComponentView interface
PaddlePaddle/PaddleFlow pull request #862
Opened 2022-10-31 09:19 UTC by StevenYangCao

### PR types

New features

### PR changes

Others 

### Describe

add Get func to ComponentView interface

2022-10-31 09:24 UTC, tornado404 approved these changes

2022-10-31 12:50 UTC, HaozhengAN requested changes

2022-10-31 12:50 UTC, HaozhengAN commented on pkg/common/schema/schema.go
>  type RuntimeView map[string][]ComponentView
runtimeView 也一起加上这两个函数先吧

2022-11-01 04:00 UTC, HaozhengAN approved these changes

2022-11-01 07:17 UTC, merged