[pipeline] update createPipeline and UpdatePipeline API: add YamlRaw parameter
PaddlePaddle/PaddleFlow pull request #900
Opened 2022-11-08 07:42 UTC by HaozhengAN

### PR types
Function optimization
### PR changes
APIs

### Describe
现在 CreatePipeline（UpdatePipeline） 接口只支持 yamlPath 这一个参数（之前未对齐），但是PDC这边不计划使用共享存储，所以如果要创建 pipeline 的话呢，就需要CreatePipeline（UpdatePipeline）接口支持 yamlRaw 参数（DSL的同步增加Create 和Update

2022-11-09 07:09 UTC, luoyuedong approved these changes

2022-11-10 04:02 UTC, Mo-Xianyuan requested changes

2022-11-10 04:02 UTC, Mo-Xianyuan commented on client/paddleflow/client.py
> +    def create_pipeline(self, fs_name, yaml_path=None, desc=None, username=None, yaml_raw=None):
fs_name在传入yaml_raw的场景下，应该是一个可选参数

2022-11-10 04:02 UTC, Mo-Xianyuan commented on client/paddleflow/client.py
> +    def update_pipeline(self, pipeline_id, fs_name, yaml_path=None, username=None, desc=None, yaml_raw=None):
同上

2022-11-10 04:02 UTC, Mo-Xianyuan commented on client/paddleflow/pipeline/pipeline_api.py
> +    def create_pipeline(self, host, fs_name, yaml_path=None, desc=None, username=None, header=None, yaml_raw=None):
fs_name在传递yaml_raw的场景下应该是可选的

2022-11-10 04:02 UTC, Mo-Xianyuan commented on pkg/apiserver/controller/pipeline/pipeline.go
> +	var fsID string
如果使用raw的话，需要Fs为空；只有不用raw的场景下，需要判断Fs。这个判断可以放在getyaml的函数中

2022-11-10 04:02 UTC, Mo-Xianyuan commented on pkg/apiserver/controller/pipeline/pipeline.go
> +
同上一评论，并且这里把原先上面的Fs校验逻辑挪下来的原因是？

2022-11-10 04:02 UTC, Mo-Xianyuan commented on pkg/apiserver/controller/pipeline/pipeline.go
> +	if request.YamlRaw != "" {
如果raw为空，校验fsname path不能非空，参数会落盘，要保持干净，避免后面参数优先级改变以后，出现脏数据污染。

2022-11-10 12:36 UTC, Mo-Xianyuan approved these changes

2022-11-10 12:59 UTC, merged